### ISSUE TITLE
Missing file Flagbit\Inxmail\Model\Config\Backend\Version

### ISSUE THREAD

**Issue by danielmartinezd** [Inxmail/inx_magento2#45]
In /vendor/inxmail/magento2-module/etc/adminhtml/system.xml you are referencing the file Flagbit\Inxmail\Model\Config\Backend\Version that does not exist in the repo.

**Comment by danielmartinezd** [comment]
Hello falco-knapp,

I used composer require.
I can see in the composer.json from Magento:
    "require": {
        "inxmail/magento2-module": "1.0"
    },

composer.lock
{
            "name": "inxmail/magento2-module",
            "version": "1.0.0",
            "source": {
                "type": "git",
                "url": "https://github.com/Inxmail/inx_magento2.git",
                "reference": "0bbf17fa06f854c680a40991a2eae6ce7300de85"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Inxmail/inx_magento2/zipball/0bbf17fa06f854c680a40991a2eae6ce7300de85",
                "reference": "0bbf17fa06f854c680a40991a2eae6ce7300de85",
                "shasum": ""
            },
            "require": {
                "magento/product-community-edition": "^2.1.8",
                "php": "~7.0.0"
            },
            "require-dev": {
                "phpunit/phpunit": "^6.2",
                "squizlabs/php_codesniffer": "3.*"
            },
            "type": "magento2-module",
            "autoload": {
                "files": [
                    "registration.php"
                ],
                "psr-4": {
                    "Flagbit\\Inxmail\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "OSL-3.0"
            ],
            "authors": [
                {
                    "name": "Peter Lelewel",
                    "email": "peter.lelewel@flagbit.de",
                    "role": "Developer"
                },
                {
                    "name": "Björn Meyer",
                    "email": "bjoern.meyer@flagbit.de",
                    "role": "Projectmanager"
                }
            ],
            "description": "Flagbit Magento 2 Inxmail Module",
            "time": "2018-01-31T07:15:33+00:00"
        },

install.json
{
        "name": "inxmail/magento2-module",
        "version": "1.0.0",
        "version_normalized": "1.0.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/Inxmail/inx_magento2.git",
            "reference": "0bbf17fa06f854c680a40991a2eae6ce7300de85"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/Inxmail/inx_magento2/zipball/0bbf17fa06f854c680a40991a2eae6ce7300de85",
            "reference": "0bbf17fa06f854c680a40991a2eae6ce7300de85",
            "shasum": ""
        },
        "require": {
            "magento/product-community-edition": "^2.1.8",
            "php": "~7.0.0"
        },
        "require-dev": {
            "phpunit/phpunit": "^6.2",
            "squizlabs/php_codesniffer": "3.*"
        },
        "time": "2018-01-31T07:15:33+00:00",
        "type": "magento2-module",
        "installation-source": "dist",
        "autoload": {
            "files": [
                "registration.php"
            ],
            "psr-4": {
                "Flagbit\\Inxmail\\": ""
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "OSL-3.0"
        ],
        "authors": [
            {
                "name": "Peter Lelewel",
                "email": "peter.lelewel@flagbit.de",
                "role": "Developer"
            },
            {
                "name": "Björn Meyer",
                "email": "bjoern.meyer@flagbit.de",
                "role": "Projectmanager"
            }
        ],
        "description": "Flagbit Magento 2 Inxmail Module"
    },

**Comment by falco-knapp** [comment]
This issue has been fixed and is available in release 1.0.1.
