### ISSUE TITLE
Something went wrong while saving this configuration - configuration cannot be saved

### ISSUE THREAD

**Issue by pmarjan** [Inxmail/inx_magento2#59]
Hello Inxmail.

When trying to save any data from Stores -> Configuration -> Inxmail -> configuration -> General, the following error is observable:

`Something went wrong while saving this configuration: Notice: Undefined index: apiKey in /var/www/html/project-name/vendor/inxmail/magento2-module/Model/Config/SystemConfig.php on line 153`

Module version is 1.1.0. 
Was added to magento by:

- composer require inxmail/magento2-module
- php bin/magento module:enable Flagbit_Inxmail
- then we executed all standard magento cli commands like: setup:upgrade, setup:di:compile, cache:clean

Magento version is 2.3.1
The error is observable at both PHP 7.1 and PHP 7.2

Please advice if we should attempt to install differently?

Regards,
Marjan.

**Comment by falco-knapp** [comment]
Hi,

Potentially the encryption and decription hasn't worked correctly (which depends on the Magento install-key). If this has changed, this could lead to this problem.

Maybe the value hasn't been saved to the DB, so this would need to be checked as well.

Could you please contact me at "connected-solutions@inxmail.de" for ease of communication?

Many thanks and regards,
Falco
