### ISSUE TITLE
Exception thrown on Magento 2.4.3-p1 with InxModule 1.1.3

### ISSUE THREAD

**Issue by falco-knapp** [Inxmail/inx_magento2#74]
==> inxmail.log <==
[2021-11-25 12:24:05] inxmail.ERROR: Notice: Undefined index: _embedded in /var/www/html/vendor/inxmail/magento2-module/Block/Adminhtml/System/Config/AttribSelectInx.php on line 73 {"trace":"#0 /var/www/html/vendor/inxmail/magento2-module/Block/Adminhtml/System/Config/AttribSelectInx.php(73): Magento\\Framework\\App\\ErrorHandler->handler()
#1 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Flagbit\\Inxmail\\Block\\Adminhtml\\System\\Config\\AttribSelectInx->_toHtml()
#2 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\\Framework\\View\\Element\\AbstractBlock->Magento\\Framework\\View\\Element\\{closure}()
#3 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\\Framework\\View\\Element\\AbstractBlock->_loadCache()
#4 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(213): Magento\\Framework\\View\\Element\\AbstractBlock->toHtml()
#5 /var/www/html/vendor/magento/module-config/view/adminhtml/templates/system/config/form/field/array.phtml(59): Magento\\Config\\Block\\System\\Config\\Form\\Field\\FieldArray\\AbstractFieldArray->renderCellTemplate()
#6 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#7 /var/www/html/vendor/magento/framework/View/Element/Template.php(273): Magento\\Framework\\View\\TemplateEngine\\Php->render()
#8 /var/www/html/vendor/magento/framework/View/Element/Template.php(303): Magento\\Framework\\View\\Element\\Template->fetchView()
#9 /var/www/html/vendor/magento/module-backend/Block/Template.php(141): Magento\\Framework\\View\\Element\\Template->_toHtml()
#10 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(260): Magento\\Backend\\Block\\Template->_toHtml()
#11 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(116): Magento\\Config\\Block\\System\\Config\\Form\\Field\\FieldArray\\AbstractFieldArray->_toHtml()
#12 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field.php(104): Magento\\Config\\Block\\System\\Config\\Form\\Field\\FieldArray\\AbstractFieldArray->_getElementHtml()
#13 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field.php(78): Magento\\Config\\Block\\System\\Config\\Form\\Field->_renderValue()
#14 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(543): Magento\\Config\\Block\\System\\Config\\Form\\Field->render()
#15 /var/www/html/vendor/magento/framework/Data/Form/Element/Text.php(41): Magento\\Framework\\Data\\Form\\Element\\AbstractElement->getHtml()
#16 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(557): Magento\\Framework\\Data\\Form\\Element\\Text->getHtml()
#17 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(98): Magento\\Framework\\Data\\Form\\Element\\AbstractElement->toHtml()
#18 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(76): Magento\\Config\\Block\\System\\Config\\Form\\Fieldset->_getChildrenElementsHtml()
#19 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(543): Magento\\Config\\Block\\System\\Config\\Form\\Fieldset->render()
#20 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(557): Magento\\Framework\\Data\\Form\\Element\\AbstractElement->getHtml()
#21 /var/www/html/vendor/magento/framework/Data/Form.php(329): Magento\\Framework\\Data\\Form\\Element\\AbstractElement->toHtml()
#22 /var/www/html/vendor/magento/framework/Data/Form.php(344): Magento\\Framework\\Data\\Form->toHtml()
#23 /var/www/html/vendor/magento/module-backend/Block/Widget/Form.php(113): Magento\\Framework\\Data\\Form->getHtml()
#24 /var/www/html/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(13): Magento\\Backend\\Block\\Widget\\Form->getFormHtml()
#25 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#26 /var/www/html/vendor/magento/framework/View/Element/Template.php(273): Magento\\Framework\\View\\TemplateEngine\\Php->render()
#27 /var/www/html/vendor/magento/framework/View/Element/Template.php(303): Magento\\Framework\\View\\Element\\Template->fetchView()
#28 /var/www/html/vendor/magento/module-backend/Block/Template.php(141): Magento\\Framework\\View\\Element\\Template->_toHtml()
#29 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\\Backend\\Block\\Template->_toHtml()
#30 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\\Framework\\View\\Element\\AbstractBlock->Magento\\Framework\\View\\Element\\{closure}()
#31 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\\Framework\\View\\Element\\AbstractBlock->_loadCache()
#32 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\\Framework\\View\\Element\\AbstractBlock->toHtml()
#33 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\\Framework\\View\\Layout->_renderBlock()
#34 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#35 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(525): Magento\\Framework\\View\\Layout->renderElement()
#36 /var/www/html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(32): Magento\\Framework\\View\\Element\\AbstractBlock->getChildHtml()
#37 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#38 /var/www/html/vendor/magento/framework/View/Element/Template.php(273): Magento\\Framework\\View\\TemplateEngine\\Php->render()
#39 /var/www/html/vendor/magento/framework/View/Element/Template.php(303): Magento\\Framework\\View\\Element\\Template->fetchView()
#40 /var/www/html/vendor/magento/module-backend/Block/Template.php(141): Magento\\Framework\\View\\Element\\Template->_toHtml()
#41 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\\Backend\\Block\\Template->_toHtml()
#42 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\\Framework\\View\\Element\\AbstractBlock->Magento\\Framework\\View\\Element\\{closure}()
#43 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\\Framework\\View\\Element\\AbstractBlock->_loadCache()
#44 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\\Framework\\View\\Element\\AbstractBlock->toHtml()
#45 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\\Framework\\View\\Layout->_renderBlock()
#46 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#47 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#48 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#49 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#50 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#51 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#52 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#53 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#54 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#55 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#56 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#57 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#58 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#59 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#60 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#61 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#62 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#63 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#64 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#65 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#66 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#67 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#68 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\\Framework\\View\\Layout->renderElement()
#69 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\\Framework\\View\\Layout->_renderContainer()
#70 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\\Framework\\View\\Layout->renderNonCachedElement()
#71 /var/www/html/vendor/magento/framework/View/Layout.php(975): Magento\\Framework\\View\\Layout->renderElement()
#72 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\\Framework\\View\\Layout->getOutput()
#73 /var/www/html/vendor/magento/framework/View/Result/Page.php(260): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()
#74 /var/www/html/vendor/magento/framework/View/Result/Layout.php(171): Magento\\Framework\\View\\Result\\Page->render()
#75 /var/www/html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(23): Magento\\Framework\\View\\Result\\Layout->renderResult()
#76 /var/www/html/vendor/magento/framework/App/Http.php(120): Magento\\Backend\\Model\\View\\Result\\Page\\Interceptor->renderResult()
#77 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http->launch()
#78 /var/www/html/pub/index.php(29): Magento\\Framework\\App\\Bootstrap->run()

**Comment by bjoern-flagbit** [comment]
**Result of the investigation:**

_I have looked at the problem, implemented a potential fix and tested it in Docker environment. There is actually no error, the try-catch block catches it and uses a standard handling. The error is not reproducible, nor does it need a fix._

_The error is recorded in the log, but has no effect. One should adjust the error message if necessary, probably leads to confusion._

_The error can only appear in the log if the API is not available or the credentials are incorrect._

How do we proceed?

**Comment by falco-knapp** [comment]
thx for the evaluation, I'm closing this issue.
